language: node_js
node_js: "22"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npx hexo clean
  - npx hexo generate

after_success:
  - npx hexo deploy
